### ISSUE TITLE
Missing window_size arg in exchange.next_observation() call

### ISSUE THREAD

**Issue by vkrot** [tensortrade-org/tensortrade#152]
Missing window_size argument, I guess it should be 
```
observation = self._exchange.next_observation(self.window_size)
```

https://github.com/tensortrade-org/tensortrade/blob/1032b3269345abcced33c91198665a651676f8c6/tensortrade/environments/trading_environment.py#L271

**Comment by vkrot** [comment]
simply adding window_size causes following error at runtime:
```
Traceback (most recent call last):
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
	 [[{{node loss/VerifyFinite/CheckNumerics}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vkrot/workspace/tensortrade/tensortrade/vkrot/notebooks/new_actions_callback.py", line 159, in <module>
    performance = strategy.run(steps=10000, episode_callback=render)
  File "/Users/vkrot/workspace/tensortrade/tensortrade/strategies/stable_baselines_strategy.py", line 155, in run
    self._agent.learn(steps, callback=self._train_callback)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 369, in learn
    cliprange_vf=cliprange_vf_now))
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 297, in _train_step
    td_map)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
	 [[node loss/VerifyFinite/CheckNumerics (defined at /Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:207) ]]

Caused by op 'loss/VerifyFinite/CheckNumerics', defined at:
  File "/Users/vkrot/workspace/tensortrade/tensortrade/vkrot/notebooks/new_actions_callback.py", line 99, in <module>
    model_kwargs=params)
  File "/Users/vkrot/workspace/tensortrade/tensortrade/strategies/stable_baselines_strategy.py", line 52, in __init__
    self._agent = self._model(policy, self._vectorized_environment, **self._model_kwargs)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 100, in __init__
    self.setup_model()
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py", line 207, in setup_model
    grads, _grad_norm = tf.clip_by_global_norm(grads, self.max_grad_norm)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/ops/clip_ops.py", line 271, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/ops/numerics.py", line 44, in verify_tensor_all_finite
    return verify_tensor_all_finite_v2(t, msg, name)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/ops/numerics.py", line 62, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 919, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
	 [[node loss/VerifyFinite/CheckNumerics (defined at /Users/vkrot/workspace/tensortrade/.venv/lib/python3.7/site-packages/stable_baselines/ppo2/ppo2.py:207) ]]
```
