### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 128 [Op:Squeeze]

### ISSUE THREAD

**Issue by sleekmike** [tensortrade-org/tensortrade#187]
**System information**

- OS Platform and Distribution: MacOS Catalina version 10.15
- TensorTrade version: tensortrade==0.2.0b1
- TensorFlow version: 2.1.0
- Python version: 3.7

**Describe the current behavior**
I am trying to run the example "train_and_evaluate.py" on my Mac and I am getting the error bellow.

**Code to reproduce the issue**  

agent.train(n_steps=200, save_path="examples/agents/")

**Other info / logs**  
 macbook@MACBOOKs-MacBook-Pro examples % python3 train_and_evaluate.py
/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
2020-02-06 06:54:54.489521: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-06 06:54:54.540689: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa476dec700 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-06 06:54:54.540722: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
====      AGENT ID: f516bab4-d294-4a60-9ec8-fe8859e9c81e      ====
====      EPISODE ID: c3a8865b-8289-432d-ac73-4f060a28eb45      ====
====      AGENT ID: 74e896ad-a9fc-427f-bb27-540783a36815      ====
====      EPISODE ID: 0f84522b-7d5d-4b61-b8a1-00e4c4bdf931      ====
Traceback (most recent call last):
  File "train_and_evaluate.py", line 108, in <module>
    agent.train(n_steps=200, save_path="examples/agents/")
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensortrade/agents/a2c_agent.py", line 202, in train
    entropy_c)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensortrade/agents/a2c_agent.py", line 140, in _apply_gradient_descent
    policy_loss_value = wsce_loss(actions, logits, sample_weight=advantages)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/keras/losses.py", line 128, in __call__
    losses, sample_weight, reduction=self._get_reduction())
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/losses_utils.py", line 107, in compute_weighted_loss
    losses, sample_weight)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/ops/losses/util.py", line 145, in scale_losses_by_sample_weight
    losses, None, sample_weight)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/ops/losses/util.py", line 97, in squeeze_or_expand_dimensions
    sample_weight = array_ops.squeeze(sample_weight, [-1])
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 3780, in squeeze
    return gen_array_ops.squeeze(input, axis, name)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9221, in squeeze
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/macbook/Desktop/TT/TT/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Can not squeeze dim[1], expected a dimension of 1, got 128 [Op:Squeeze]

**Comment by giranntu** [comment]
occur this error too. Seems this build is not ready.
@notadamking may guide how to run the example?

**Comment by devmev** [comment]
It seems like the problem is based on the shape of the given advantages Tensor for the loss function "policy_loss_value = wsce_loss(actions, logits, sample_weight=advantages)" in a2c_agent.py. I haven't figured out the solution as I am not so familiar with the advantages methode.

**Comment by jonatrey** [comment]
Same issue here, you can reproduce by simply running the notebook train_and_evaluate.ipynb

**Comment by giranntu** [comment]
yea if apply the @cashmesh one line for argumax, it worked. 
The reason might because when using the sparse_categorical_crossentropy loss, your targets should be integer targets. If you have categorical targets, you should use categorical_crossentropy

So need to convert the labels to integers.

**Comment by sleekmike** [comment]
I still experiencing this error on ubuntu 18

**Comment by giranntu** [comment]
@sleekmike  it is nothing related to the os version, but the tf version and need to reinstall the package(since we changed the lib code for that one line.)

`returns = tf.reshape(returns, [batch_size, 1])`

1. After inserting this code, **make sure your tf version is 2.1.0** . 
2. reinstall the package by running the command `!python3 -m pip install -e .. -U`

**Comment by mpresence** [comment]
> @sleekmike it is nothing related to the os version, but the tf version and need to reinstall the package(since we changed the lib code for that one line.)
> 
> `returns = tf.reshape(returns, [batch_size, 1])`
> 
> 1. After inserting this code, **make sure your tf version is 2.1.0** .
> 2. reinstall the package by running the command `!python3 -m pip install -e .. -U`  (you can find this command in example notebook first line)

Hello not sure which line needs replacing?

**Comment by sleekmike** [comment]
Hello @giranntu, thanks this fixed my issue :)
But unfortunately I am now getting this issue even after installing the latest version of Tensortrade.

ModuleNotFoundError: No module named 'stochastic'
