### ISSUE TITLE
Simulated exchange tutorial not working

### ISSUE THREAD

**Issue by sword134** [tensortrade-org/tensortrade#239]
**System information**

- Have I written custom code (as opposed to using example directory): Using the tutorial from towardsdatascience
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04): Windows 10
- TensorTrade version: Latest
- TensorFlow version: Latest
- Python version: 3.6

**Describe the current behavior**
When going through the tutorial on towardsdatascience you are presented with the following bit of code:

```
from tensortrade.exchanges.simulated import SimulatedExchange
df = pd.read_csv('D:\ReinforcementLearning\Tensortrade\Combined DIAGLDDAX\DIA Basics.csv')
exchange = SimulatedExchange(data_frame=df, base_instrument='USD')

```
However the SimulatedExchange function doesn't exist and as a result I create it in a new file called simulated.py in the tensortrade/Exchanges library. In that file I put the following:

```
from typing import Callable, Union
from decimal import Decimal

from tensortrade.base import Component, TimedIdentifiable
from tensortrade.instruments import TradingPair
from tensortrade.data import Module
from tensortrade.data import Forward

from tensortrade.exchanges.exchange import Exchange
import pandas as pd
import numpy as np

class SimulatedExchange(Exchange):
    """An exchange, in which the price history is based off the supplied data frame and
    trade execution is largely decided by the designated slippage model.
    If the `data_frame` parameter is not supplied upon initialization, it must be set before
    the exchange can be used within a trading environment.
    """

    def __init__(self, data_frame: pd.DataFrame = None, **kwargs):
        super().__init__(
            dtype=self.default('dtype', np.float32),
            feature_pipeline=self.default('feature_pipeline', None)
        )

        self._commission_percent = self.default('commission_percent', 0.3, kwargs)
        self._base_precision = self.default('base_precision', 2, kwargs)
        self._instrument_precision = self.default('instrument_precision', 8, kwargs)
        self._min_trade_size = self.default('min_trade_size', 1e-6, kwargs)
        self._max_trade_size = self.default('max_trade_size', 1e6, kwargs)

        self._initial_balance = self.default('initial_balance', 1e4, kwargs)
        self._observation_columns = self.default(
            'observation_columns',
            ['open', 'high', 'low', 'close', 'volume'],
            kwargs
        )
        self._price_column = self.default('price_column', 'close', kwargs)
        self._window_size = self.default('window_size', 1, kwargs)
        self._pretransform = self.default('pretransform', True, kwargs)
        self._price_history = None

        self.data_frame = self.default('data_frame', data_frame)

        model = self.default('slippage_model', 'uniform', kwargs)
        self._slippage_model = slippage.get(model) if isinstance(model, str) else model()
```
Running the code now gives me the following error instead: 

```
C:\Users\Tomas_000>D:\Anaconda\envs\RL\python.exe -u "d:\ReinforcementLearning\Tensortrade\TensortradeTest.py"
2020-07-21 17:32:12.090599: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "d:\ReinforcementLearning\Tensortrade\TensortradeTest.py", line 6, in <module>
    exchange = SimulatedExchange(data_frame=df, base_instrument='USD')
  File "D:\Anaconda\envs\RL\lib\site-packages\tensortrade\base\component.py", line 22, in __call__
    instance.__init__(*args, **kwargs)
  File "D:\Anaconda\envs\RL\lib\site-packages\tensortrade\exchanges\simulated.py", line 23, in __init__
    feature_pipeline=self.default('feature_pipeline', None)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

**Comment by mwbrulhardt** [comment]
This is a previous version of TT and is now outdated.
