### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'stochastic'

### ISSUE THREAD

**Issue by huydhoang** [tensortrade-org/tensortrade#246]
**System information**

- Have I written custom code (as opposed to using example directory): No
- OS Platform and Distribution: Pop OS (Ubuntu 20.04)
- TensorTrade version: 0.2.0rc0
- TensorFlow version: 1.13.1
- Python version: 3.6.10 Miniconda

**Describe the current behavior**
Getting `ModuleNotFoundError: No module named 'stochastic'`

**Describe the expected behavior**
Code sample runs without errors.

**Code to reproduce the issue**  
```
import random

import tensortrade.stochastic as sp


data = sp.gbm(
    base_price=100,
    base_volume=5,
    start_date="2010-01-01",
    times_to_generate=1000,
    time_frame="1H",
)

data.close.plot()

```

**Other info / logs**  
```
Traceback (most recent call last):
  File "generate_ts.py", line 3, in <module>
    import tensortrade.stochastic as sp
  File "./lib/python3.6/site-packages/tensortrade/__init__.py", line 3, in <module>
    from . import environments
  File "./lib/python3.6/site-packages/tensortrade/environments/__init__.py", line 1, in <module>
    from .trading_environment import TradingEnvironment
  File "./lib/python3.6/site-packages/tensortrade/environments/trading_environment.py", line 25, in <module>
    import tensortrade.exchanges as exchanges
  File "./lib/python3.6/site-packages/tensortrade/exchanges/__init__.py", line 9, in <module>
    from . import simulated
  File "./lib/python3.6/site-packages/tensortrade/exchanges/simulated/__init__.py", line 3, in <module>
    from .stochastic_exchange import StochasticExchange
  File "./lib/python3.6/site-packages/tensortrade/exchanges/simulated/stochastic_exchange.py", line 18, in <module>
    from stochastic.noise import GaussianNoise
ModuleNotFoundError: No module named 'stochastic'
```

**Comment by mwbrulhardt** [comment]
Also did you install stochastic?

**Comment by huydhoang** [comment]
Maybe this is the cause, I'll make another attempt when I can. Thanks
