### ISSUE TITLE
Example from the docs not working at all - what format is required as data input?

### ISSUE THREAD

**Issue by rufusroger** [tensortrade-org/tensortrade#263]
**System information**

- Have I written custom code (as opposed to using example directory): **No - I copied Example 1:1**
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04): **Ubuntu 20.04**
- TensorTrade version: **1.0.0b0**
- TensorFlow version: **2.3.1**
- Python version: **3.8.5**

**Describe the current behavior**
I try to get a minimal working example to run, for which I copied the example code from the [docs](https://www.tensortrade.org/en/latest/examples/train_and_evaluate.html). While CCD does not work at all (see logs). When I follow the into the source code, I can only find "gemini" as a key for CCD, what irritates me like crazy. 
In regards to the following output (shown in the docs), I assume the the pandas DataFrame need the first(?) column to be _'date': Timestamp('2017-07-01 11:00:00')_? 
```
{'internal': {'coinbase:/USD-BTC': 2509.17,
  'coinbase:/USD:/free': 10000.0,
  'coinbase:/USD:/locked': 0.0,
  'coinbase:/USD:/total': 10000.0,
  'coinbase:/BTC:/free': 10.0,
  'coinbase:/BTC:/locked': 0.0,
  'coinbase:/BTC:/total': 10.0,
  'coinbase:/BTC:/worth': 25091.7,
  'net_worth': 35091.7},
 'external': {'lr': nan, 'rsi': nan, 'macd': 0.0},
 'renderer': {'date': Timestamp('2017-07-01 11:00:00'),
  'open': 2505.56,
  'high': 2513.38,
  'low': 2495.12,
  'close': 2509.17,
  'volume': 287000.32}}
```
Using the ccxt package to gather exchange data, I am unable to get the **int timestamp** to **Timestamp object** for further testing. If i use a pandas DataFrame with the following format: 

```
print(data.info)
<bound method DataFrame.info of        BTC:open  BTC:high   BTC:low  BTC:close   BTC:volume                date
0      13715.65  13715.65  13400.01   13529.01   443.356199 2018-01-01 00:00:00
...         ...       ...       ...        ...          ...                 ...
25613  19183.41  19231.22  19163.46   19225.10   392.526540 2020-12-07 11:00:00

[25614 rows x 6 columns]>
```
Since I spent hours and days to get anything from tensortrader to output something other than errors, I better ask here.

**Describe the expected behavior**
I would expect a minimal working example, in order to at least be able to inspect e.g. required formats of the input data. 

**Code to reproduce the issue**  
```
cdd = CryptoDataDownload()
data = cdd.fetch("Coinbase", "USD", "BTC", "1h")

def macd(price: Stream[float], fast: float, slow: float, signal: float) -> Stream[float]:
    fm = price.ewm(span=fast, adjust=False).mean()
    sm = price.ewm(span=slow, adjust=False).mean()
    md = fm - sm
    signal = md - md.ewm(span=signal, adjust=False).mean()
    return signal


def rsi(price: Stream[float], period: float) -> Stream[float]:
    r = price.diff()
    upside = r.clamp_min(0).abs()
    downside = r.clamp_max(0).abs()
    rs = upside.ewm(alpha=1 / period).mean() / downside.ewm(alpha=1 / period).mean()
    return 100*(1 - (1 + rs) ** -1)


features = []
for c in data.columns[1:]:
    s = Stream.source(list(data[c]), dtype="float").rename(data[c].name)
    features += [s]

cp = Stream.select(features, lambda s: s.name == "close")

features = [
    cp.log().diff().rename("lr"),
    rsi(cp, period=20).rename("rsi"),
    macd(cp, fast=10, slow=50, signal=5).rename("macd")
]

feed = DataFeed(features)
feed.compile()
for i in range(5):
    print(feed.next())

coinbase = Exchange("coinbase", service=execute_order)(
    Stream.source(list(data["close"]), dtype="float").rename("USD-BTC")
)

portfolio = Portfolio(USD, [
    Wallet(coinbase, 10000 * USD),
    Wallet(coinbase, 10 * BTC)
])


renderer_feed = DataFeed([
    Stream.source(list(data["date"])).rename("date"),
    Stream.source(list(data["open"]), dtype="float").rename("open"),
    Stream.source(list(data["high"]), dtype="float").rename("high"),
    Stream.source(list(data["low"]), dtype="float").rename("low"),
    Stream.source(list(data["close"]), dtype="float").rename("close"),
    Stream.source(list(data["volume"]), dtype="float").rename("volume")
])


env = default.create(
    portfolio=portfolio,
    action_scheme="managed-risk",
    reward_scheme="risk-adjusted",
    feed=feed,
    renderer_feed=renderer_feed,
    renderer=default.renderers.PlotlyTradingChart(),
    window_size=20
)

env.observer.feed.next()
```

**Other info / logs**  
```
Traceback (most recent call last):
  File "/home/ruphus/PythonProjects/DDDQNTrader/test.py", line 14, in <module>
    data = cdd.fetch("Coinbase", "USD", "BTC", "1h")
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/tensortrade/data/cdd.py", line 147, in fetch
    return self.fetch_default(exchange_name,
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/tensortrade/data/cdd.py", line 68, in fetch_default
    df = df.drop(["Symbol"], axis=1)
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
    return super().drop(
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3887, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3921, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5284, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['Symbol'] not found in axis"

Process finished with exit code 1
```
With ccxt gathered data from binance within the further up explained DataFrame format, I receive this error:
```
Traceback (most recent call last):
  File "/home/ruphus/PythonProjects/DDDQNTrader/test.py", line 40, in <module>
    cp = Stream.select(features, lambda s: s.name == "close")
  File "/home/ruphus/PythonProjects/venv/lib/python3.8/site-packages/tensortrade/feed/core/base.py", line 312, in select
    raise Exception("No stream satisfies selector condition.")
Exception: No stream satisfies selector condition.
```

**Comment by stefanalexandru02** [comment]
There is an error with Coinbase I think (I got the same error as you). Fetch the data from Bitstamp instead and it should work

**Comment by nicomon24** [comment]
I got the error too, and Bitstamp is not working now. 
This is an easy issue, basically the CSV headers changed from https://www.cryptodatadownload.com

You need to edit "Symbol" -> "symbol" and the datetime format from "%Y-%m-%d %I-%p" -> "%Y-%m-%d %H:%M:%S"
I adding a PR to fix this

**Comment by mwbrulhardt** [comment]
Merged the PR so this should be fixed.
