### ISSUE TITLE
BUG: AttributeError: 'IterableStream' object has no attribute 'mul'

### ISSUE THREAD

**Issue by sadimoodi** [tensortrade-org/tensortrade#347]
Thanks for the wonderful library.
Dependencies:
ray==0.8.7
python3.7

All of my other dependent packages are as per your requirements.txt

I am running the following code:
cdd = CryptoDataDownload()
btc_data = cdd.fetch("Bitfinex", "USD", "BTC", "1h").add_prefix("BTC:")
price_stream =  Stream.source(list(btc_data['BTC:close']), dtype="float").rename("USD-BTC")
exch_opts = ExchangeOptions( commission = 0.015 )
myEx = Exchange("myEx", service=execute_order, options=exch_opts)(price_stream)
ta.add_all_ta_features(
    btc_data,
    colprefix="BTC:",
    **{k: "BTC:" + k for k in ['open', 'high', 'low', 'close', 'volume']}, fillna=True
)
feed = DataFeed([Stream.source(list(btc_data[c]), dtype="float").rename(c) for c in btc_data.columns])
cash = Wallet(myEx, 200 * USD)
asset = Wallet(myEx, 0 * BTC)
portfolio = Portfolio(USD, [
    cash,
    asset ])
reward_scheme = PBR( price = price_stream )
action_scheme = BSH( 
       cash = cash, 
       asset = asset 
).attach( reward_scheme )
 renderer_feed = DataFeed([
        Stream.source(list(btc_data['BTC:close']), dtype="float").rename("price"),
        Stream.sensor(action_scheme, lambda s: s.action, dtype="float").rename("action")
    ])
def create_env(config):

    environment = default.create(
        feed=feed,
        portfolio=portfolio,
        action_scheme=action_scheme,
        reward_scheme=reward_scheme,
        renderer_feed=renderer_feed,
        renderer='screen-log',
        window_size=config["window_size"],
        max_allowed_loss=0.6
    )
    return environment

register_env("TradingEnv", create_env)

After i run training of the agent, i get the following error:

(pid=1285) WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
(pid=1285) Instructions for updating:
(pid=1285) non-resource variables are not supported in the long term
2021-11-02 06:53:47,105	ERROR trial_runner.py:523 -- Trial PPO_TradingEnv_9d6d9_00000: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trial_runner.py", line 471, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/ray_trial_executor.py", line 430, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.7/dist-packages/ray/worker.py", line 1538, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PPO.train() (pid=1285, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 439, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 474, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 478, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py", line 88, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 479, in __init__
    super().__init__(config, logger_creator)
  File "/usr/local/lib/python3.7/dist-packages/ray/tune/trainable.py", line 245, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 643, in setup
    self._init(self.config, self.env_creator)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer_template.py", line 102, in _init
    env_creator, self._policy, config, self.config["num_workers"])
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/agents/trainer.py", line 713, in _make_workers
    logdir=self.logdir)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/evaluation/worker_set.py", line 67, in __init__
    RolloutWorker, env_creator, policy, 0, self._local_config)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/evaluation/worker_set.py", line 296, in _make_worker
    extra_python_environs=extra_python_environs)
  File "/usr/local/lib/python3.7/dist-packages/ray/rllib/evaluation/rollout_worker.py", line 324, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "<ipython-input-34-1dd4de382976>", line 11, in create_env
  File "/usr/local/lib/python3.7/dist-packages/tensortrade/env/default/__init__.py", line 61, in create
    min_periods=min_periods
  File "/usr/local/lib/python3.7/dist-packages/tensortrade/core/component.py", line 41, in __call__
    instance.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensortrade/env/default/observers.py", line 194, in __init__
    internal_group = Stream.group(_create_internal_streams(portfolio)).rename("internal")
  File "/usr/local/lib/python3.7/dist-packages/tensortrade/env/default/observers.py", line 75, in _create_internal_streams
    sources += _create_wallet_source(wallet, include_worth=(symbol != base_symbol))
  File "/usr/local/lib/python3.7/dist-packages/tensortrade/env/default/observers.py", line 50, in _create_wallet_source
    worth = price.mul(total_balance).rename('worth')
**AttributeError: 'IterableStream' object has no attribute 'mul'**

I made sure that my data does NOT contain NaN in the price stream.
I checked your code in observer.py and the line generating the error: 
**worth = price.mul(total_balance).rename('worth')**
i placed a print before this line (print (type(price))
It looks like the price object that was passed here was of type <class 'types.IterableStream'> which does NOT include the mul function, instead the price type should be <class 'tensortrade.feed.core.base.IterableStream'>

when taking the line :
price = Stream.select(wallet.exchange.streams(), lambda node: node.name.endswith(symbol))
to an outside block it correctly returns class 'tensortrade.feed.core.base.IterableStream object.
I wonder what is causing this behavior in your code?

**Comment by sadimoodi** [comment]
it turns out that all of the above code should be inside "def create_env(config):" block to be able to run.

**Comment by giancds** [comment]
I'm getting the same error, with the code inside `create_env` and using `IntradayObserver`.
